### ISSUE TITLE
Add Spotify features: Problematic tracks

### ISSUE THREAD

**Issue by owen910715** [serkansulun/midi-emotion#3]
What should I do if there are several problematic tracks when I'm running run.py?

**Comment by serkansulun** [comment]
It can be normal. Can you try getting the features for those individual tracks?

**Comment by owen910715** [comment]
Oh I see. But a bigger one occured. The program just completely stopped at a certain track with no errors, any solutions to that?
Thanks :)

**Comment by serkansulun** [comment]
I think after a certain quota is exceeded, Spotify blocks access, so the script hangs. I pushed a new commit, which uses a file that keeps an incomplete list of features obtained from Spotify, so that the script can be run multiple times and it will continue from where it has left.

When the script hangs, i.e. the user quota is exceeded, you can re-run the script some time later, request an increase in quota, or use a different account with different client ID and secret.

I'm sorry that I cannot share the features directly, due to legal restrictions.
