### ISSUE TITLE
When I run train.py, I get an error:FileNotFoundError: [Errno 2] No such file or directory: '../data_files/lpd_5/lpd_5_full_transposable' Could you please tell me how to get the file:.. /data_files/lpd_5/lpd_5_full_transposable?

### ISSUE THREAD

**Issue by xlblthh** [serkansulun/midi-emotion#4]
Hi, @serkansulun. Thank you for your great work.
When I run train.py, I get an error:FileNotFoundError: [Errno 2] No such file or directory: '../data_files/lpd_5/lpd_5_full_transposable'
Could you please tell me how to get the file:.. /data_files/lpd_5/lpd_5_full_transposable?

**Comment by serkansulun** [comment]
Hi, sorry for the late reply. After you download and extract all necessary data, and run the script to create the full dataset, you need to preprocess it by going to the ```src/data``` folder and running ```preprocess_pianorolls.py```

I updated the readme, so the steps should be clearer now.

**Comment by xlblthh** [comment]
Thank you very much for your reply! 
     You mean that I need to create the corresponding path and put the data into it, right?
     May I ask the way:.. Is lpd_5 in /data_files/lpd_5/lpd_5_full_transposable the dataset Lakh pianoroll 5 full dataset as stated in readme.md? There is also a maps.pt in the path: /data_files/lpd_5. Is this used in.. Is there mappings.pt in /output/vanilla?
     In addition, I would like to ask you some questions: When I run train.py, top-1 and top-5, as well as the data of emotional effect evaluation by regression model, are not displayed, so how should I obtain these data?

**Comment by serkansulun** [comment]
Yes, just follow the readme.

```lpd_5_full_transposable``` is just the preprocessed version of Lakh pianoroll 5 full dataset.

```maps.pt``` is created during data preprocessing, it maps musical events to indices for easier transposition. ```mappings.pt``` is used by the model, it maps musical events to tokens so that they can be processed by the transformer.

The accuracies are calculated though not printed in order not to clutter the output. You should edit the following and add the accuracy:
 https://github.com/serkansulun/midi-emotion/blob/df0152fa4e1d03faa77ab87c123cfffe191b1271/src/train.py#L417-L421

To get the emotion evaluation you first need to train a regression model, and then run it on generated samples. Check out ```config.py```.

Sorry that this repository was only meant to generate the music, and not to exactly replicate the results in the article (although it's possible with some modifications and training). I'm dealing with other projects at the moment so I don't have time to modify it to accomplish the latter. Good luck!

**Comment by xlblthh** [comment]
Thank you very much for taking time out of your busy schedule to answer my questions!
     I would also like to ask you a question: can you tell me the steps on how to use transfer_model.py for transfer learning?

**Comment by serkansulun** [comment]
Just fill in the old and new model names:

https://github.com/serkansulun/midi-emotion/blob/df0152fa4e1d03faa77ab87c123cfffe191b1271/src/models/transfer_model.py#L13-L14

If you don't have a new model template, you can create it by running 
```python train.py --log_step 1 --max_step 1 ...```
as it's explain at the top of the script.

**Comment by xlblthh** [comment]
Ok, thanks for your answer! I also want to confirm what I said earlier... /data_files/lpd_5 The path and maps.pt are generated in preprocess_pianorolls.py, right?

**Comment by serkansulun** [comment]
Yes.

**Comment by xlblthh** [comment]
Thank you for your reply! I also want to ask you, when running train.py, the training becomes stable to a certain extent, and how to modify the learning rate? Finally, the effect is that the training is completed when the val_loss reaches about 0.7, right? Not the value of loss. When I run train.py, I only want to train the last continue_concat condition model, if I don't need to train the first three models. Can the continue_concat model I trained with train.py run generate.py and give certain mood value to generate four midi format music as in the pre-training?
